name: pn-codegen docker image build and publish

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      image_tag: ${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Package
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.image_tag }}
      
      - name: Print image tag
        run: |
          echo "Image tag ${{ env.image_tag }}"