name: pn-codegen docker image build and publish

on:
  push:
    branches: [ "develop", "main", "releases/**" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "develop", "main" ]

env:
  CONTAINER_REGISTRY: ghcr.io

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      image_tag: ${{ github.repository }}:${{ github.sha }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Login to GitHub Package
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository }}

      - name: Build and push container image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Print image tags and labels
        run: |
          echo "Image tags: ${{ steps.meta.outputs.tags }}"
          echo "Image labels: ${{ steps.meta.outputs.labels }}"
